// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  user_id,
  title
) VALUES (
  $1, $2
)
RETURNING id, user_id, title, completed, created_at
`

type CreateTaskParams struct {
	UserID pgtype.UUID
	Title  string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.UserID, arg.Title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
  id,
  user_id,
  title,
  completed,
  created_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT
  id,
  title,
  completed,
  created_at
FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListTasksByUserRow struct {
	ID        pgtype.UUID
	Title     string
	Completed bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListTasksByUser(ctx context.Context, userID pgtype.UUID) ([]ListTasksByUserRow, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByUserRow
	for rows.Next() {
		var i ListTasksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET completed = $2
WHERE id = $1
RETURNING id, completed
`

type UpdateTaskStatusParams struct {
	ID        pgtype.UUID
	Completed bool
}

type UpdateTaskStatusRow struct {
	ID        pgtype.UUID
	Completed bool
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (UpdateTaskStatusRow, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Completed)
	var i UpdateTaskStatusRow
	err := row.Scan(&i.ID, &i.Completed)
	return i, err
}
